databases:
  - name: driveasy
    databaseName: driveasy
    user: driveasy_user

services:
  - type: web
    name: driveasy
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: driveasy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false